# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/jazzsewera/pre-commit-dotnet-hooks.git
  rev: v0.1
  hooks:
  - id: dotnet-reformat
    name: dotnet-reformat-cc
    files: 'cc/src/.*\.cs'
    args: ['cc/']
  - id: dotnet-reformat
    name: dotnet-reformat-cn
    files: 'cn/src/.*\.cs'
    args: ['cn/']
  - id: dotnet-reformat
    name: dotnet-reformat-ms
    files: 'ms/src/.*\.cs'
    args: ['ms/']
  - id: dotnet-reformat
    name: dotnet-reformat-nn
    files: 'nn/src/.*\.cs'
    args: ['nn/']
- repo: https://github.com/jazzsewera/pre-commit-message-check-hook.git
  rev: v0.2.0
  hooks:
  - id: commit-message-check
    args: ['-r', '^#[0-9]+ [A-Z].*|Merge.*']
