# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/jazzsewera/pre-commit-dotnet-hooks.git
  rev: v0.1
  hooks:
  - id: dotnet-reformat
    name: dotnet-reformat-cc
    files: 'cc/src/.*'
    args: ['cc/']
  - id: dotnet-reformat
    name: dotnet-reformat-cn
    files: 'cn/src/.*'
    args: ['cn/']
  - id: dotnet-reformat
    name: dotnet-reformat-ms
    files: 'ms/src/.*'
    args: ['ms/']
  - id: dotnet-reformat
    name: dotnet-reformat-nn
    files: 'nn/src/.*'
    args: ['nn/']
