repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.1.7
  hooks:
  - id: remove-crlf
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.3.0
  hooks:
  - id: end-of-file-fixer
- repo: https://github.com/jazzsewera/pre-commit-message-check-hook.git
  rev: v0.2.0
  hooks:
  - id: commit-message-check
    args: ['-r', '^#[0-9]+ [A-Z].*|Merge.*']
